version: "3.9"
services:
  server:
    build: ./backend
    container_name: server_container
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/node_modules:/app/node_modules
      - ./backend:/app
    environment:
      CONNECTION_STRING: mongodb+srv://cshehani44:0Z2pS23vimyo7xEc@cluster-legianpastry.rk8d9cu.mongodb.net/<databaseName>?retryWrites=true&w=majority
      JWT_SECRET: hahufahiuhajshdkja1a45
      PORT: 5000

  client:
    build: ./frontend
    container_name: client_nginx
    ports:
      - "80:80"
    depends_on:
      - server
