services:
  server:
    build:
      context: ../backend
    container_name: server_container
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
      - ../backend/node_modules:/app/node_modules
      - ../backend/uploads:/app/uploads
    env_file:
      - ../backend/.env
    networks:
      - app-network

  client:
    build:
      context: ../frontend
    container_name: client_nginx
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
